services:
  # Test Database
  db_test:
    image: postgres:15-alpine
    container_name: geostory_test_db
    environment:
      POSTGRES_USER: geostory_user
      POSTGRES_PASSWORD: geostory_pass
      POSTGRES_DB: geostory_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geostory_user -d geostory_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - geostory_test_data:/var/lib/postgresql/data

volumes:
  geostory_test_data:
